using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data;
using System.Diagnostics;

namespace UpLoadNews
{
    public class proshowjoin
    {
        #region // khai bao bien dau tien
        private string _head = "Photodex(R) ProShow(TM) Producer Show File Version=0\n"
                    + "proshowMajorVersion=9.0\n"
                    + "proshowVersion=3769\n"
                    + "title=ProShow Slideshow\n"
                    + "fileName=My Computer/C:/Users/BN/Desktop/ProShow Slideshow.psh\n"
                    + "description=\"\"\n"
                    + "showAspect=1\n"
                    + "showSizeX=16\n"
                    + "showSizeY=9\n"
                    + "loop=1\n"
                    + "loopRestart=1\n"
                    + "displaySizeX=704\n"
                    + "displaySizeY=528\n"
                    + "videoSizeX=720\n"
                    + "videoSizeY=480\n"
                    + "videoFrameRate=29970\n"
                    + "videoBitRate=1120000\n"
                    + "videoMuxBitRate=1394400\n"
                    + "outputImageSizeX=1024\n"
                    + "outputImageSizeY=768\n"
                    + "outputQuality=80\n"
                    + "toolbarEnable=1\n"
                    + "allowQuit=1\n"
                    + "allowPlay=1\n"
                    + "allowTime=1\n"
                    + "allowRestart=1\n"
                    + "allowSave=1\n"
                    + "allowSaveAll=1\n"
                    + "allowPrint=1\n"
                    + "allowPrintAll=1\n"
                    + "allowCopy=1\n"
                    + "allowSaver=1\n"
                    + "allowCta=1\n"
                    + "ctaLabel=ProShow Info\n"
                    + "ctaURL=http://www.photodex.com/\n"
                    + "background=1\n"
                    + "bgOutlineColor=0\n"
                    + "bgSizeMode=1\n"
                    + "bgColorizeColor=8421504\n"
                    + "waterOpacity=128\n"
                    + "waterZoom=10000\n"
                    + "waterColorizeColor=8421504\n"
                    + "musicVolumeOffset=100\n"
                    + "defaultCellVolumeOffset=100\n"
                    + "defaultCellFadeIn=100\n"
                    + "defaultCellFadeOut=100\n"
                    + "defaultMusicVolumeOffset=50\n"
                    + "defaultMusicFadeIn=100\n"
                    + "defaultMusicFadeOut=100\n"
                    + "maxDispWidth=800\n"
                    + "maxDispHeight=600\n"
                    + "maxRender=1\n"
                    + "maxRenderWidth=800\n"
                    + "maxRenderHeight=600\n"
                    + "normalizePreset=1\n"
                    + "randomTransitions=FFFFFFFF:FFFFFFFF:FFFFFFFF:FFFFFFFF:FFFFFFFF:FFFFFFFF:FFFFFFFF:FFFFFFFF:FFFFFFFF:FFFFFFFF\n";
        #endregion

        public static string getLocalInProshow(string local)
        {
           
            return local.Replace("\\", "/");
        }
        public string _ChuyenSlide(int n)
        {
            string kq = "cell["+n.ToString()+ "].useCustomTransition="+ n.ToString()+ "\n"
                + "cell["+n.ToString()+ "].customTransitionName = Grayscale Doors - Horizontal\n"
                + "cell["+n.ToString()+ "].customTransition.imageEnable = 1\n"
                + "cell["+n.ToString()+ "].customTransition.nrOfImages = 9\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].imageEnable = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].name = Solid 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].replaceableTemplate = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].sizeMode = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].outlineColor = 16777215\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].aspectX = 4\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].aspectY = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].videoVolume = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].objectId = -1846590429\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].videoSpeed = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].outlineSize = 10\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].shadowSize = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].shadowOpacity = 128\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].maskChannel = 10\n"
                //+ "cell["+n.ToString()+  @"].customTransition.images[0].filterName = ""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[0].savedFilterName =""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[0].motionFilterName =""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[0].motionFilterNameIn =""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[0].motionFilterNameOut =""\n"
                 + "cell["+n.ToString()+ "].customTransition.images[0].useGradient = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].gradient.type = 6\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].gradient.p1x = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].gradient.p1y = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].gradient.defaultResX = 1280\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].gradient.defaultResY = 720\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].gradient.colorMapSize = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].gradient.colormap[0].color = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].gradient.colormap[1].color = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].gradient.colormap[1].index = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].nrOfKeyframes = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].timeSegment = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].offsetX = -5300\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].zoomX = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].zoomY = 16000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].panAccelType = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].lockAR = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[0].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].timestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].timeSegment = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].segmentTimestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].offsetX = 5300\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].zoomX = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].zoomY = 16000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].lockAR = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[0].keyframes[1].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].imageEnable = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].name = Solid 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].replaceableTemplate = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].sizeMode = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].outlineColor = 16777215\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].aspectX = 4\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].aspectY = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].videoVolume = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].objectId = 1836282646\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].videoSpeed = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].outlineSize = 10\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].shadowSize = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].shadowOpacity = 128\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].maskChannel = 10\n"
                //+ "cell["+n.ToString()+  @"].customTransition.images[1].filterName =""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[1].savedFilterName =""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[1].motionFilterName = ""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[1].motionFilterNameIn =""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[1].motionFilterNameOut = ""\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].useGradient = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].gradient.type = 6\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].gradient.p1x = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].gradient.p1y = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].gradient.defaultResX = 1280\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].gradient.defaultResY = 720\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].gradient.colorMapSize = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].gradient.colormap[0].color = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].gradient.colormap[1].color = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].gradient.colormap[1].index = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].nrOfKeyframes = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].timeSegment = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].offsetX = 5300\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].zoomX = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].zoomY = 16000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].panAccelType = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].lockAR = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[0].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].timestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].timeSegment = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].segmentTimestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].offsetX = -5300\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].zoomX = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].zoomY = 16000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].lockAR = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[1].keyframes[1].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].imageEnable = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].name = Solid 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].replaceableTemplate = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].sizeMode = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].outlineColor = 16777215\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].aspectX = 4\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].aspectY = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].videoVolume = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].objectId = 1836282647\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].videoSpeed = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].outlineSize = 10\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].shadowSize = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].shadowOpacity = 128\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].isMaskingLayer = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].maskChannel = 10\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].maskLayerCount = 1\n"
                //+ "cell["+n.ToString()+ @"].customTransition.images[2].filterName =""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[2].savedFilterName =""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[2].motionFilterName =""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[2].motionFilterNameIn =""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[2].motionFilterNameOut =""\n"
                 + "cell["+n.ToString()+ "].customTransition.images[2].useGradient = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].gradient.type = 6\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].gradient.p1x = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].gradient.p1y = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].gradient.defaultResX = 1280\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].gradient.defaultResY = 720\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].gradient.colorMapSize = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].gradient.colormap[0].color = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].gradient.colormap[1].color = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].gradient.colormap[1].index = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].nrOfKeyframes = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].timestamp = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].timeSegment = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].segmentTimestamp = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].zoomX = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].zoomY = 11000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].zoomXAccelType = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].zoomYAccelType = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].lockAR = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[0].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].timestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].timeSegment = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].segmentTimestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].zoomX = 10600\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].zoomY = 11000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].panAccelType = 1\n"
                + "cell["+n.ToString()+"].customTransition.images[2].keyframes[1].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+"].customTransition.images[2].keyframes[1].zoomXAccelType = 1\n"
                +"cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].lockAR = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[2].keyframes[1].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].imageEnable = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].replaceableTemplate = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].sizeMode = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].colorizeColor = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].colorizeStrength = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].outlineColor = 16777215\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].aspectX = 4\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].aspectY = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].videoVolume = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].objectId = 1836282644\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].transitionStyleId = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].videoSpeed = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].outlineSize = 10\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].shadowSize = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].shadowOpacity = 128\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].maskChannel = 10\n"
                //+ "cell["+n.ToString()+ @"].customTransition.images[3].filterName =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[3].savedFilterName =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[3].motionFilterName =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[3].motionFilterNameIn =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[3].motionFilterNameOut = ""\n"
                 + "cell["+n.ToString()+ "].customTransition.images[3].nrOfKeyframes = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].timeSegment = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].zoomX = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].zoomY = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].lockAR = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].brightness = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].blackpoint = 750\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].whitepoint = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[0].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].timestamp = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].timeSegment = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].segmentTimestamp = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].attributeMask = 36832\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].zoomX = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].zoomY = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].lockAR = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].brightness = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].blackpoint = 750\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].whitepoint = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[1].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].timestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].timeSegment = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].segmentTimestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].zoomX = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].zoomY = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].lockAR = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[3].keyframes[2].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].imageEnable = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].name = Solid 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].replaceableTemplate = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].sizeMode = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].outlineColor = 16777215\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].aspectX = 4\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].aspectY = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].videoVolume = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].objectId = -1846590423\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].videoSpeed = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].outlineSize = 10\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].shadowSize = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].shadowOpacity = 128\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].isMaskingLayer = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].maskChannel = 10\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].maskLayerCount = 1\n"
                //+ "cell["+n.ToString()+ @"].customTransition.images[4].filterName =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[4].savedFilterName =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[4].motionFilterName =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[4].motionFilterNameIn =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[4].motionFilterNameOut =""\n"
                 + "cell["+n.ToString()+ "].customTransition.images[4].useGradient = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].gradient.type = 6\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].gradient.p1x = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].gradient.p1y = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].gradient.defaultResX = 1280\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].gradient.defaultResY = 720\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].gradient.colorMapSize = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].gradient.colormap[0].color = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].gradient.colormap[1].color = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].gradient.colormap[1].index = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].nrOfKeyframes = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].timeSegment = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].offsetX = -10600\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].zoomX = 10600\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].zoomY = 11000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].panAccelType = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].zoomXAccelType = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].zoomYAccelType = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].lockAR = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].blur = 400\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[0].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].timestamp = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].timeSegment = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].segmentTimestamp = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].offsetX = -5300\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].zoomX = 10600\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].zoomY = 11000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].panAccelType = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].lockAR = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].blur = 400\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[1].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].timestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].timeSegment = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].segmentTimestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].offsetX = -5300\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].zoomX = 10600\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].zoomY = 11000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].lockAR = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].blur = 400\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[4].keyframes[2].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].imageEnable = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].templateImageId = 6\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].replaceableTemplate = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].sizeMode = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].colorizeColor = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].colorizeStrength = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].outlineColor = 16777215\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].aspectX = 4\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].aspectY = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].videoVolume = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].objectId = -1846590421\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].transitionStyleId = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].videoSpeed = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].outlineSize = 10\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].shadowSize = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].shadowOpacity = 128\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].maskChannel = 10\n"
                //+ "cell["+n.ToString()+ @"].customTransition.images[5].filterName =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[5].savedFilterName =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[5].motionFilterName =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[5].motionFilterNameIn =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[5].motionFilterNameOut =""\n"
                + "cell["+n.ToString()+"].customTransition.images[5].nrOfKeyframes = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].timeSegment = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].zoomX = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].zoomY = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].lockAR = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].blackpoint = -500\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].whitepoint = 500\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].colorize = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].colorizeColor = -8355712\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[0].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].timestamp = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].timeSegment = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].segmentTimestamp = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].attributeMask = 33632\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].zoomX = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].zoomY = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].lockAR = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].colorize = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].colorizeColor = -8355712\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[1].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].timestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].timeSegment = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].segmentTimestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].zoomX = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].zoomY = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].lockAR = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].blur = 500\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].colorize = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].colorizeColor = -8355712\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[5].keyframes[2].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].imageEnable = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].name = Solid 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].replaceableTemplate = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].sizeMode = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].outlineColor = 16777215\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].aspectX = 4\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].aspectY = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].videoVolume = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].objectId = -1846590427\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].videoSpeed = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].outlineSize = 10\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].shadowSize = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].shadowOpacity = 128\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].isMaskingLayer = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].maskChannel = 10\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].maskLayerCount = 1\n"
                //+ "cell["+n.ToString()+ @"].customTransition.images[6].filterName =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[6].savedFilterName =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[6].motionFilterName =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[6].motionFilterNameIn =""\n"
                // + "cell["+n.ToString()+@"].customTransition.images[6].motionFilterNameOut =""\n"
                 + "cell["+n.ToString()+ "].customTransition.images[6].useGradient = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].gradient.type = 6\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].gradient.p1x = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].gradient.p1y = 1000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].gradient.defaultResX = 1280\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].gradient.defaultResY = 720\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].gradient.colorMapSize = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].gradient.colormap[0].color = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].gradient.colormap[1].color = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].gradient.colormap[1].index = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].nrOfKeyframes = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].timeSegment = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].offsetX = 10600\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].zoomX = 10600\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].zoomY = 11000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].panAccelType = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].zoomXAccelType = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].zoomYAccelType = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].lockAR = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].blur = 400\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[0].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].timestamp = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].timeSegment = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].segmentTimestamp = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].offsetX = 5300\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].zoomX = 10600\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].zoomY = 11000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].panAccelType = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].lockAR = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].blur = 400\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[1].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].timestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].timeSegment = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].segmentTimestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].offsetX = 5300\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].zoomX = 10600\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].zoomY = 11000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].lockAR = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].blur = 400\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].colorizeColor = 8421504\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[6].keyframes[2].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].imageEnable = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].templateImageId = 6\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].replaceableTemplate = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].sizeMode = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].colorizeColor = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].colorizeStrength = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].outlineColor = 16777215\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].aspectX = 4\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].aspectY = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].videoVolume = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].objectId = -1846590425\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].transitionStyleId = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].videoSpeed = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].outlineSize = 10\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].shadowSize = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].shadowOpacity = 128\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].maskChannel = 10\n"
                //+ "cell["+n.ToString()+  @"].customTransition.images[7].filterName = ""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[7].savedFilterName = ""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[7].motionFilterName = ""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[7].motionFilterNameIn = ""\n"
                // + "cell["+n.ToString()+ @"].customTransition.images[7].motionFilterNameOut =""\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].nrOfKeyframes = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].timeSegment = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].zoomX = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].zoomY = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].lockAR = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].blackpoint = -500\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].whitepoint = 500\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].colorize = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].colorizeColor = -8355712\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[0].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].timestamp = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].timeSegment = 2\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].segmentTimestamp = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].attributeMask = 33728\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].zoomX = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].zoomY = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].lockAR = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].colorize = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].colorizeColor = -8355712\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[1].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].timestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].timeSegment = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].segmentTimestamp = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].attributeMask = -1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].zoomX = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].zoomY = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].panAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].zoomXAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].zoomYAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].rotationAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].tiltVAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].tiltHAccelType = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].motionSmoothness = 5000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].lockAR = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].transparency = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].blur = 500\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].audioFade = 2000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].colorize = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].colorizeColor = -8355712\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].colorizeStrength = 10000\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].shadowOffsetX = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[7].keyframes[2].shadowOffsetY = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].imageEnable = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].templateImageId = 6\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].replaceableTemplate = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].sizeMode = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].colorizeColor = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].colorizeStrength = 0\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].outlineColor = 16777215\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].aspectX = 4\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].aspectY = 3\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].videoVolume = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].objectId = 1836282645\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].transitionStyleId = 1\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].videoSpeed = 100\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].outlineSize = 10\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].shadowSize = 70\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].shadowOpacity = 128\n"
                + "cell["+n.ToString()+ "].customTransition.images[8].maskChannel = 10\n"
                 //+  "cell["+n.ToString()+ @"].customTransition.images[8].filterName =""\n"
                 //+ "cell["+n.ToString()+ @"].customTransition.images[8].savedFilterName =""\n"
                 //+ "cell["+n.ToString()+ @"].customTransition.images[8].motionFilterName =""\n"
                 //+ "cell["+n.ToString()+ @"].customTransition.images[8].motionFilterNameIn = ""\n"
                 //+ "cell["+n.ToString()+ @"].customTransition.images[8].motionFilterNameOut = ""\n"
                 + "cell[" + n.ToString() + "].customTransition.images[8].nrOfKeyframes = 2\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].timeSegment = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].attributeMask = -1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].zoomX = 10000\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].zoomY = 10000\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].panAccelType = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].zoomXAccelType = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].zoomYAccelType = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].rotationAccelType = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].tiltVAccelType = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].tiltHAccelType = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].motionSmoothness = 5000\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].lockAR = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].transparency = 0\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].audioFade = 2000\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].colorizeColor = 8421504\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].colorizeStrength = 10000\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].shadowOffsetX = 70\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[0].shadowOffsetY = 70\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].timestamp = 10000\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].timeSegment = 3\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].segmentTimestamp = 10000\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].attributeMask = -1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].zoomX = 10000\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].zoomY = 10000\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].panAccelType = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].zoomXAccelType = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].zoomYAccelType = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].rotationAccelType = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].tiltVAccelType = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].tiltHAccelType = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].motionSmoothness = 5000\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].lockAR = 1\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].transparency = 0\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].audioFade = 2000\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].colorizeColor = 8421504\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].colorizeStrength = 10000\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].shadowOffsetX = 70\n"
                + "cell[" + n.ToString() + "].customTransition.images[8].keyframes[1].shadowOffsetY = 70\n"
                + "cell[" + n.ToString() + "].customTransition.background = 1\n"
                + "cell[" + n.ToString() + "].customTransition.bgDefault = 1\n"
                + "cell[" + n.ToString() + "].customTransition.bgSizeMode = 1\n"
                + "cell[" + n.ToString() + "].customTransition.bgColorizeColor = 8421504\n"
                + "cell[" + n.ToString() + "].customTransition.sound.useDefault = 1\n"
                + "cell[" + n.ToString() + "].customTransition.sound.volume = 100\n"
                + "cell[" + n.ToString() + "].customTransition.sound.fadeIn = 100\n"
                + "cell[" + n.ToString() + "].customTransition.sound.fadeOut = 100\n"
                + "cell[" + n.ToString() + "].customTransition.sound.async = 1\n"
                + "cell[" + n.ToString() + "].customTransition.sound.musicUseDefault = 1\n"
                + "cell[" + n.ToString() + "].customTransition.sound.musicVolume = 50\n"
                + "cell[" + n.ToString() + "].customTransition.sound.musicFadeIn = 100\n"
                + "cell[" + n.ToString() + "].customTransition.sound.musicFadeOut = 100\n"
                + "cell[" + n.ToString() + "].customTransition.sound.normalizeCustom = 0\n"
                + "cell[" + n.ToString() + "].customTransition.sound.normalizePreset = 0\n"
                + "cell[" + n.ToString() + "].customTransition.musicVolumeOffset = 50\n"
                + "cell[" + n.ToString() + "].customTransition.time = 3000\n"
                + "cell[" + n.ToString() + "].customTransition.transId = 2\n"
                + "cell[" + n.ToString() + "].customTransition.includeGlobalCaptions = 1\n";
            return kq;
        }
        public string _MusicBg(string localFoder,string music)
           {
            string kq = "makeFileLocalFolder=" + getLocalInProshow(localFoder) + "\n"
                    + "sounds=1\n"
                    + "sound[0].file=../../../../" + getLocalInProshow(music) + "\n"
                    + "sound[0].length=72000000\n"
                    + "sound[0].useDefault=1\n"
                    + "sound[0].volume=25\n"
                    + "sound[0].normalizeCustom=0\n"
                    + "sound[0].normalizePreset=0\n"
                    + "sound[0].volumeProfile.nrOfPoints=2\n"
                    + "sound[0].volumeProfile.point[0].timestamp=0\n"
                    + "sound[0].volumeProfile.point[0].volume=1000\n"
                    + "sound[0].volumeProfile.point[1].timestamp=175072\n"
                    + "sound[0].volumeProfile.point[1].volume=1000\n";
            return kq;
           }
        public static Double getDuration(string path)
        {
            try
            {
                string localFFmpeg = Application.StartupPath + "\\Win32bit\\ffmpeg.exe";

                StreamReader errorreader;

                Process ffmpeg = new Process();

                ffmpeg.StartInfo.UseShellExecute = false;
                ffmpeg.StartInfo.ErrorDialog = false;
                ffmpeg.StartInfo.RedirectStandardError = true;

                ffmpeg.StartInfo.FileName = localFFmpeg;
                ffmpeg.StartInfo.Arguments = "-i \"" + path + "\"";
                ffmpeg.StartInfo.CreateNoWindow = true;

                ffmpeg.Start();

                errorreader = ffmpeg.StandardError;

                ffmpeg.WaitForExit();

                string result = errorreader.ReadToEnd();

                string durations = result.Substring(result.IndexOf("Duration: ") + ("Duration: ").Length, ("00:00:00.00").Length);
                TimeSpan time = TimeSpan.Parse(durations);
                double du = time.TotalSeconds;
                return du;
            }
            catch (Exception)
            {


            }
            return 0;
        }

        public string _JoinVideo(bool checkjoinmc,DataTable m_video)
        {
            string kq = "";
            kq = "cells="+m_video.Rows.Count.ToString() + "\n";
            int i = 0;
            foreach (DataRow r in m_video.Rows)
            {
                // time tung slide
                TimesFile timefile = new TimesFile();
                double times = timefile.GetTime(r["FileVideo"].ToString()) * 1000; //(getDuration(r["FileVideo"].ToString()) * 1000);
                if (times < 10000)
                {
                    times = 14000;
                }               
                // time chuyen canh
                string timenext = "";
                string chuyencanh = "";
                if(checkjoinmc==true)
                {
                    if(i>2)
                    {
                       // timenext ="cell[" + i.ToString() + "].transTime=3000\n";
                        chuyencanh = _ChuyenSlide(i);
                       
                    }
                    else
                    {
                        times = getDuration(r["FileVideo"].ToString()) * 1000;
                    }
                }
                else
                {
                   // timenext = "cell[" + i.ToString() + "].transTime=3000\n";
                    chuyencanh = _ChuyenSlide(i);

                }
                kq = kq + "cell[" + i.ToString() + "].nrOfImages=1\n"
                + "cell[" + i.ToString() + "].images[0].image=../../../../" + getLocalInProshow(r["FileVideo"].ToString()) + "\n"
                + "cell[" + i.ToString() + "].images[0].imageEnable=1\n"
                + "cell[" + i.ToString() + "].images[0].name=" + i.ToString() + "\n"
                + "cell[" + i.ToString() + "].images[0].replaceableTemplate=1\n"
                + "cell[" + i.ToString() + "].images[0].sizeMode=1\n"
                + "cell[" + i.ToString() + "].images[0].colorizeColor=8421504\n"
                + "cell[" + i.ToString() + "].images[0].colorizeStrength=10000\n"
                + "cell[" + i.ToString() + "].images[0].outlineColor=16777215\n"
                + "cell[" + i.ToString() + "].images[0].aspectX=4\n"
                + "cell[" + i.ToString() + "].images[0].aspectY=3\n"
                + "cell[" + i.ToString() + "].images[0].isVideo=1\n"
                + "cell[" + i.ToString() + "].images[0].videoVolume=100\n"
                + "cell[" + i.ToString() + "].images[0].videoLength=130970\n"
                + "cell[" + i.ToString() + "].images[0].objectId=3\n"
                + "cell[" + i.ToString() + "].images[0].videoSpeed=100\n"
                + "cell[" + i.ToString() + "].images[0].outlineSize=10\n"
                + "cell[" + i.ToString() + "].images[0].shadowSize=70\n"
                + "cell[" + i.ToString() + "].images[0].shadowOpacity=128\n"
                + "cell[" + i.ToString() + "].images[0].maskChannel=10\n"
                //+ @"cell[" + i.ToString() + @"].images[0].filterName=""\n"
                //+ @"cell[" + i.ToString() + @"].images[0].savedFilterName=""\n"
                //+ @"cell[" + i.ToString() + @"].images[0].motionFilterName=""\n"
                //+ @"cell[" + i.ToString() + @"].images[0].motionFilterNameIn=""\n"
                //+ @"cell[" + i.ToString() + @"].images[0].motionFilterNameOut=""\n"
                + "cell[" + i.ToString() + "].images[0].nrOfKeyframes=2\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].timeSegment=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].attributeMask=-1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].zoomX=10000\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].zoomY=10000\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].panAccelType=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].zoomXAccelType=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].zoomYAccelType=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].rotationAccelType=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].tiltVAccelType=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].tiltHAccelType=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].motionSmoothness=5000\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].lockAR=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].transparency=0\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].audioFade=2000\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].colorizeColor=8421504\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].colorizeStrength=10000\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].shadowOffsetX=70\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[0].shadowOffsetY=70\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].timestamp=10000\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].timeSegment=3\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].segmentTimestamp=10000\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].attributeMask=-1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].zoomX=10000\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].zoomY=10000\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].panAccelType=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].zoomXAccelType=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].zoomYAccelType=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].rotationAccelType=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].tiltVAccelType=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].tiltHAccelType=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].motionSmoothness=5000\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].lockAR=1\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].transparency=0\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].audioFade=2000\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].colorizeColor=8421504\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].colorizeStrength=10000\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].shadowOffsetX=70\n"
                + "cell[" + i.ToString() + "].images[0].keyframes[1].shadowOffsetY=70\n"
                + "cell[" + i.ToString() + "].background=1\n"
                + "cell[" + i.ToString() + "].bgDefault=1\n"
                + "cell[" + i.ToString() + "].bgSizeMode=1\n"
                + "cell[" + i.ToString() + "].bgColorizeColor=8421504\n"
                + "cell[" + i.ToString() + "].sound.useDefault=1\n"
                + "cell[" + i.ToString() + "].sound.volume=100\n"
                + "cell[" + i.ToString() + "].sound.fadeIn=100\n"
                + "cell[" + i.ToString() + "].sound.fadeOut=100\n"
                + "cell[" + i.ToString() + "].sound.async=1\n"
                + "cell[" + i.ToString() + "].sound.musicUseDefault=1\n"
                + "cell[" + i.ToString() + "].sound.musicVolume=50\n"
                + "cell[" + i.ToString() + "].sound.musicFadeIn=100\n"
                + "cell[" + i.ToString() + "].sound.musicFadeOut=100\n"
                + "cell[" + i.ToString() + "].sound.normalizeCustom=0\n"
                + "cell[" + i.ToString() + "].sound.normalizePreset=0\n"
                + "cell[" + i.ToString() + "].musicVolumeOffset=50\n"
                + "cell[" + i.ToString() + "].time=" + times.ToString() + "\n"
                + "cell[" + i.ToString() + "].transId=2\n"
                + timenext
                + "cell[" + i.ToString() + "].includeGlobalCaptions=1\n";
                //+chuyencanh;
                i = i + 1;
            }
            kq = kq + "modifierCount=0\n";
            return kq;
        }

        public string _CreateJoinFile(bool checkjoinmc,string localFoder, string music, DataTable m_video,string outputpsh)
        {
            StringBuilder content = new StringBuilder();
            content.Append(_head);
            content.Append(_MusicBg(localFoder,music));
            content.Append(_JoinVideo(checkjoinmc,m_video));
            content.Replace("\r\n", "\n").Replace("\r", "\n").Replace("\n", "\r\n");
            try
            {
                using (StreamWriter outputFile = new StreamWriter(File.Open(outputpsh, FileMode.Create), Encoding.Default))
                {
                    outputFile.Write(content.ToString());
                    return outputpsh;
                }
            }
            catch (Exception e)
            {
                MessageBox.Show(e.ToString());
                return "";
            }
        }

        public string _CreateJoinFile2(bool checkjoinmc, string localFoder, string music, DataTable m_video, string outputpsh)
        {
            StringBuilder content = new StringBuilder();
            content.Append(_head);
          //  content.Append(_MusicBg(localFoder, music));
            content.Append(_JoinVideo(checkjoinmc, m_video));
            content.Replace("\r\n", "\n").Replace("\r", "\n").Replace("\n", "\r\n");
            try
            {
                using (StreamWriter outputFile = new StreamWriter(File.Open(outputpsh, FileMode.Create), Encoding.Default))
                {
                    outputFile.Write(content.ToString());
                    return outputpsh;
                }
            }
            catch (Exception e)
            {
                MessageBox.Show(e.ToString());
                return "";
            }
        }
    }
}
